# Generated by Django 2.1.1 on 2020-08-25 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.CharField(max_length=2000)),
                ('banner_xlarge', models.ImageField(upload_to='subcategory_banners')),
                ('banner_large', models.ImageField(blank=True, upload_to='subcategory_banners')),
                ('banner_nslarge', models.ImageField(blank=True, upload_to='subcategory_banners')),
                ('banner_normal', models.ImageField(blank=True, upload_to='subcategory_banners')),
                ('banner_medium', models.ImageField(blank=True, upload_to='subcategory_banners')),
                ('banner_small', models.ImageField(blank=True, upload_to='subcategory_banners')),
                ('banner_xsmall', models.ImageField(blank=True, upload_to='subcategory_banners')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.Category')),
            ],
        ),
    ]
