# Generated by Django 2.1.1 on 2020-08-27 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200827_0548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=2000)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True)),
                ('discount', models.FloatField(blank=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('badge', models.CharField(max_length=50)),
                ('video', models.FileField(blank=True, upload_to='videos')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_size', models.IntegerField(blank=True)),
                ('clothing_size', models.CharField(blank=True, max_length=40)),
                ('material', models.CharField(blank=True, max_length=50)),
                ('item_variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.ItemVariant')),
            ],
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='banner_image',
        ),
        migrations.AddField(
            model_name='image',
            name='subcategory',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='banner_image', to='store.SubCategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.SubCategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.SubCategoryClass'),
        ),
        migrations.AddField(
            model_name='image',
            name='item_variant',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.ItemVariant'),
        ),
    ]
