# Generated by Django 2.1.1 on 2020-08-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200827_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariant',
            name='name',
            field=models.CharField(default='something edition', max_length=100),
            preserve_default=False,
        ),
    ]
