# Generated by Django 2.1.1 on 2020-08-27 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_itemvariant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='item_variant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='store.ItemVariant'),
        ),
    ]
