# Generated by Django 2.1.1 on 2020-08-27 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20200827_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specifications_list', to='store.Item'),
        ),
    ]
