# Generated by Django 2.1.1 on 2020-08-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_specification_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('items', models.ManyToManyField(default=None, to='store.Item')),
            ],
        ),
    ]
