# Generated by Django 2.1.1 on 2020-08-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_collection_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='subcategoryclass',
            name='slug',
            field=models.SlugField(blank=True, max_length=300),
        ),
    ]
