# Generated by Django 2.1.1 on 2020-08-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200827_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(to='store.Category'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ManyToManyField(to='store.SubCategory'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='subcategory_class',
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory_class',
            field=models.ManyToManyField(to='store.SubCategoryClass'),
        ),
    ]
