# Generated by Django 2.1.1 on 2020-08-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20200827_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='subcategory',
            new_name='subcategories',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='subcategory_class',
            new_name='subcategory_classes',
        ),
    ]
