# Generated by Django 2.1.1 on 2020-08-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20200828_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(to='store.Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='subcategories',
            field=models.ManyToManyField(to='store.SubCategory'),
        ),
    ]
