# Generated by Django 2.1.1 on 2020-08-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20200828_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariant',
            name='in_stock',
            field=models.IntegerField(default=0),
        ),
    ]
