# Generated by Django 2.1.1 on 2020-08-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_itemvariant_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='clothing_size',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='specification',
            name='material',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='specification',
            name='shoe_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
