# Generated by Django 2.1.1 on 2020-09-13 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_collection_homepage_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='offer',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='store.Offer'),
        ),
        migrations.AddField(
            model_name='collection',
            name='offer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.Offer'),
        ),
        migrations.AddField(
            model_name='item',
            name='offer',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item', to='store.Offer'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='offer',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subcategory', to='store.Offer'),
        ),
    ]
