# Generated by Django 2.1.1 on 2020-09-13 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_collection_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='item',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='offer',
        ),
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Category'),
        ),
        migrations.AddField(
            model_name='offer',
            name='collection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Collection'),
        ),
        migrations.AddField(
            model_name='offer',
            name='item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Item'),
        ),
        migrations.AddField(
            model_name='offer',
            name='subcategory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.SubCategory'),
        ),
    ]
