# Generated by Django 2.1.1 on 2020-09-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20200913_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='homepage_banner',
            field=models.BooleanField(default=False),
        ),
    ]
