# Generated by Django 2.1.1 on 2020-08-15 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='bodyimages')),
                ('upload_nslarge', models.ImageField(blank=True, upload_to='bodyimages')),
                ('upload_normal', models.ImageField(blank=True, upload_to='bodyimages')),
                ('upload_medium', models.ImageField(blank=True, upload_to='bodyimages')),
                ('upload_small', models.ImageField(blank=True, upload_to='bodyimages')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('banner_xlarge', models.ImageField(upload_to='category_banners')),
                ('banner_large', models.ImageField(blank=True, upload_to='category_banners')),
                ('banner_nslarge', models.ImageField(blank=True, upload_to='category_banners')),
                ('banner_normal', models.ImageField(blank=True, upload_to='category_banners')),
                ('banner_medium', models.ImageField(blank=True, upload_to='category_banners')),
                ('banner_small', models.ImageField(blank=True, upload_to='category_banners')),
                ('banner_xsmall', models.ImageField(blank=True, upload_to='category_banners')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('main', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
                ('slug', models.SlugField(blank=True, default='', max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_xlarge', models.ImageField(upload_to='slides')),
                ('image_large', models.ImageField(blank=True, upload_to='slides')),
                ('image_nslarge', models.ImageField(blank=True, upload_to='slides')),
                ('image_normal', models.ImageField(blank=True, upload_to='slides')),
                ('image_medium', models.ImageField(blank=True, upload_to='slides')),
                ('image_small', models.ImageField(blank=True, upload_to='slides')),
                ('image_xsmall', models.ImageField(blank=True, upload_to='slides')),
                ('caption_title', models.CharField(max_length=100)),
                ('caption_body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(default='Admin', max_length=100)),
                ('banner_xlarge', models.ImageField(upload_to='banners')),
                ('banner_large', models.ImageField(blank=True, upload_to='banners')),
                ('banner_nslarge', models.ImageField(blank=True, upload_to='banners')),
                ('banner_normal', models.ImageField(blank=True, upload_to='banners')),
                ('banner_medium', models.ImageField(blank=True, upload_to='banners')),
                ('banner_small', models.ImageField(blank=True, upload_to='banners')),
                ('banner_xsmall', models.ImageField(blank=True, upload_to='banners')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(default='', max_length=500)),
                ('body', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('structure', models.CharField(default='', max_length=15)),
                ('featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
                ('searchSlug', models.SlugField(blank=True, max_length=500)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('author', models.CharField(blank=True, max_length=500)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, default='', max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.Post')),
                ('rating', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('total_reviews', models.IntegerField(default=0)),
                ('rating_sum', models.IntegerField(default=0)),
                ('rating_index', models.FloatField(default=0.0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='posts',
            field=models.ManyToManyField(to='blog.Post'),
        ),
        migrations.AddField(
            model_name='question',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
        migrations.AddField(
            model_name='image',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Group'),
        ),
    ]
