# Generated by Django 2.1.1 on 2020-09-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Group', max_length=20)),
                ('link', models.TextField()),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
    ]
